//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SleepMonitorClient.SleepServiceRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SleepEntry", Namespace="http://sleepmonitor.org/")]
    [System.SerializableAttribute()]
    public partial class SleepEntry : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        private System.DateTime SleepTimeField;
        
        private System.DateTime WakeTimeField;
        
        private int SleepScoreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NotesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime SleepTime {
            get {
                return this.SleepTimeField;
            }
            set {
                if ((this.SleepTimeField.Equals(value) != true)) {
                    this.SleepTimeField = value;
                    this.RaisePropertyChanged("SleepTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime WakeTime {
            get {
                return this.WakeTimeField;
            }
            set {
                if ((this.WakeTimeField.Equals(value) != true)) {
                    this.WakeTimeField = value;
                    this.RaisePropertyChanged("WakeTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int SleepScore {
            get {
                return this.SleepScoreField;
            }
            set {
                if ((this.SleepScoreField.Equals(value) != true)) {
                    this.SleepScoreField = value;
                    this.RaisePropertyChanged("SleepScore");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Notes {
            get {
                return this.NotesField;
            }
            set {
                if ((object.ReferenceEquals(this.NotesField, value) != true)) {
                    this.NotesField = value;
                    this.RaisePropertyChanged("Notes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://sleepmonitor.org/", ConfigurationName="SleepServiceRef.SleepServiceSoap")]
    public interface SleepServiceSoap {
        
        // CODEGEN: Generating message contract since element name notes from namespace http://sleepmonitor.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://sleepmonitor.org/AddSleepEntry", ReplyAction="*")]
        SleepMonitorClient.SleepServiceRef.AddSleepEntryResponse AddSleepEntry(SleepMonitorClient.SleepServiceRef.AddSleepEntryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sleepmonitor.org/AddSleepEntry", ReplyAction="*")]
        System.Threading.Tasks.Task<SleepMonitorClient.SleepServiceRef.AddSleepEntryResponse> AddSleepEntryAsync(SleepMonitorClient.SleepServiceRef.AddSleepEntryRequest request);
        
        // CODEGEN: Generating message contract since element name notes from namespace http://sleepmonitor.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://sleepmonitor.org/UpdateSleepEntry", ReplyAction="*")]
        SleepMonitorClient.SleepServiceRef.UpdateSleepEntryResponse UpdateSleepEntry(SleepMonitorClient.SleepServiceRef.UpdateSleepEntryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sleepmonitor.org/UpdateSleepEntry", ReplyAction="*")]
        System.Threading.Tasks.Task<SleepMonitorClient.SleepServiceRef.UpdateSleepEntryResponse> UpdateSleepEntryAsync(SleepMonitorClient.SleepServiceRef.UpdateSleepEntryRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllSleepEntriesResult from namespace http://sleepmonitor.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://sleepmonitor.org/GetAllSleepEntries", ReplyAction="*")]
        SleepMonitorClient.SleepServiceRef.GetAllSleepEntriesResponse GetAllSleepEntries(SleepMonitorClient.SleepServiceRef.GetAllSleepEntriesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sleepmonitor.org/GetAllSleepEntries", ReplyAction="*")]
        System.Threading.Tasks.Task<SleepMonitorClient.SleepServiceRef.GetAllSleepEntriesResponse> GetAllSleepEntriesAsync(SleepMonitorClient.SleepServiceRef.GetAllSleepEntriesRequest request);
        
        // CODEGEN: Generating message contract since element name DeleteSleepEntryResult from namespace http://sleepmonitor.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://sleepmonitor.org/DeleteSleepEntry", ReplyAction="*")]
        SleepMonitorClient.SleepServiceRef.DeleteSleepEntryResponse DeleteSleepEntry(SleepMonitorClient.SleepServiceRef.DeleteSleepEntryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sleepmonitor.org/DeleteSleepEntry", ReplyAction="*")]
        System.Threading.Tasks.Task<SleepMonitorClient.SleepServiceRef.DeleteSleepEntryResponse> DeleteSleepEntryAsync(SleepMonitorClient.SleepServiceRef.DeleteSleepEntryRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddSleepEntryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddSleepEntry", Namespace="http://sleepmonitor.org/", Order=0)]
        public SleepMonitorClient.SleepServiceRef.AddSleepEntryRequestBody Body;
        
        public AddSleepEntryRequest() {
        }
        
        public AddSleepEntryRequest(SleepMonitorClient.SleepServiceRef.AddSleepEntryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://sleepmonitor.org/")]
    public partial class AddSleepEntryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime sleepTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime wakeTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int sleepScore;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string notes;
        
        public AddSleepEntryRequestBody() {
        }
        
        public AddSleepEntryRequestBody(System.DateTime sleepTime, System.DateTime wakeTime, int sleepScore, string notes) {
            this.sleepTime = sleepTime;
            this.wakeTime = wakeTime;
            this.sleepScore = sleepScore;
            this.notes = notes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddSleepEntryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddSleepEntryResponse", Namespace="http://sleepmonitor.org/", Order=0)]
        public SleepMonitorClient.SleepServiceRef.AddSleepEntryResponseBody Body;
        
        public AddSleepEntryResponse() {
        }
        
        public AddSleepEntryResponse(SleepMonitorClient.SleepServiceRef.AddSleepEntryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://sleepmonitor.org/")]
    public partial class AddSleepEntryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddSleepEntryResult;
        
        public AddSleepEntryResponseBody() {
        }
        
        public AddSleepEntryResponseBody(string AddSleepEntryResult) {
            this.AddSleepEntryResult = AddSleepEntryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateSleepEntryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateSleepEntry", Namespace="http://sleepmonitor.org/", Order=0)]
        public SleepMonitorClient.SleepServiceRef.UpdateSleepEntryRequestBody Body;
        
        public UpdateSleepEntryRequest() {
        }
        
        public UpdateSleepEntryRequest(SleepMonitorClient.SleepServiceRef.UpdateSleepEntryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://sleepmonitor.org/")]
    public partial class UpdateSleepEntryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime sleepTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime wakeTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int sleepScore;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string notes;
        
        public UpdateSleepEntryRequestBody() {
        }
        
        public UpdateSleepEntryRequestBody(int id, System.DateTime sleepTime, System.DateTime wakeTime, int sleepScore, string notes) {
            this.id = id;
            this.sleepTime = sleepTime;
            this.wakeTime = wakeTime;
            this.sleepScore = sleepScore;
            this.notes = notes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateSleepEntryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateSleepEntryResponse", Namespace="http://sleepmonitor.org/", Order=0)]
        public SleepMonitorClient.SleepServiceRef.UpdateSleepEntryResponseBody Body;
        
        public UpdateSleepEntryResponse() {
        }
        
        public UpdateSleepEntryResponse(SleepMonitorClient.SleepServiceRef.UpdateSleepEntryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://sleepmonitor.org/")]
    public partial class UpdateSleepEntryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdateSleepEntryResult;
        
        public UpdateSleepEntryResponseBody() {
        }
        
        public UpdateSleepEntryResponseBody(string UpdateSleepEntryResult) {
            this.UpdateSleepEntryResult = UpdateSleepEntryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllSleepEntriesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllSleepEntries", Namespace="http://sleepmonitor.org/", Order=0)]
        public SleepMonitorClient.SleepServiceRef.GetAllSleepEntriesRequestBody Body;
        
        public GetAllSleepEntriesRequest() {
        }
        
        public GetAllSleepEntriesRequest(SleepMonitorClient.SleepServiceRef.GetAllSleepEntriesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllSleepEntriesRequestBody {
        
        public GetAllSleepEntriesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllSleepEntriesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllSleepEntriesResponse", Namespace="http://sleepmonitor.org/", Order=0)]
        public SleepMonitorClient.SleepServiceRef.GetAllSleepEntriesResponseBody Body;
        
        public GetAllSleepEntriesResponse() {
        }
        
        public GetAllSleepEntriesResponse(SleepMonitorClient.SleepServiceRef.GetAllSleepEntriesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://sleepmonitor.org/")]
    public partial class GetAllSleepEntriesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SleepMonitorClient.SleepServiceRef.SleepEntry[] GetAllSleepEntriesResult;
        
        public GetAllSleepEntriesResponseBody() {
        }
        
        public GetAllSleepEntriesResponseBody(SleepMonitorClient.SleepServiceRef.SleepEntry[] GetAllSleepEntriesResult) {
            this.GetAllSleepEntriesResult = GetAllSleepEntriesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteSleepEntryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteSleepEntry", Namespace="http://sleepmonitor.org/", Order=0)]
        public SleepMonitorClient.SleepServiceRef.DeleteSleepEntryRequestBody Body;
        
        public DeleteSleepEntryRequest() {
        }
        
        public DeleteSleepEntryRequest(SleepMonitorClient.SleepServiceRef.DeleteSleepEntryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://sleepmonitor.org/")]
    public partial class DeleteSleepEntryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public DeleteSleepEntryRequestBody() {
        }
        
        public DeleteSleepEntryRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteSleepEntryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteSleepEntryResponse", Namespace="http://sleepmonitor.org/", Order=0)]
        public SleepMonitorClient.SleepServiceRef.DeleteSleepEntryResponseBody Body;
        
        public DeleteSleepEntryResponse() {
        }
        
        public DeleteSleepEntryResponse(SleepMonitorClient.SleepServiceRef.DeleteSleepEntryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://sleepmonitor.org/")]
    public partial class DeleteSleepEntryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DeleteSleepEntryResult;
        
        public DeleteSleepEntryResponseBody() {
        }
        
        public DeleteSleepEntryResponseBody(string DeleteSleepEntryResult) {
            this.DeleteSleepEntryResult = DeleteSleepEntryResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SleepServiceSoapChannel : SleepMonitorClient.SleepServiceRef.SleepServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SleepServiceSoapClient : System.ServiceModel.ClientBase<SleepMonitorClient.SleepServiceRef.SleepServiceSoap>, SleepMonitorClient.SleepServiceRef.SleepServiceSoap {
        
        public SleepServiceSoapClient() {
        }
        
        public SleepServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SleepServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SleepServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SleepServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SleepMonitorClient.SleepServiceRef.AddSleepEntryResponse SleepMonitorClient.SleepServiceRef.SleepServiceSoap.AddSleepEntry(SleepMonitorClient.SleepServiceRef.AddSleepEntryRequest request) {
            return base.Channel.AddSleepEntry(request);
        }
        
        public string AddSleepEntry(System.DateTime sleepTime, System.DateTime wakeTime, int sleepScore, string notes) {
            SleepMonitorClient.SleepServiceRef.AddSleepEntryRequest inValue = new SleepMonitorClient.SleepServiceRef.AddSleepEntryRequest();
            inValue.Body = new SleepMonitorClient.SleepServiceRef.AddSleepEntryRequestBody();
            inValue.Body.sleepTime = sleepTime;
            inValue.Body.wakeTime = wakeTime;
            inValue.Body.sleepScore = sleepScore;
            inValue.Body.notes = notes;
            SleepMonitorClient.SleepServiceRef.AddSleepEntryResponse retVal = ((SleepMonitorClient.SleepServiceRef.SleepServiceSoap)(this)).AddSleepEntry(inValue);
            return retVal.Body.AddSleepEntryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SleepMonitorClient.SleepServiceRef.AddSleepEntryResponse> SleepMonitorClient.SleepServiceRef.SleepServiceSoap.AddSleepEntryAsync(SleepMonitorClient.SleepServiceRef.AddSleepEntryRequest request) {
            return base.Channel.AddSleepEntryAsync(request);
        }
        
        public System.Threading.Tasks.Task<SleepMonitorClient.SleepServiceRef.AddSleepEntryResponse> AddSleepEntryAsync(System.DateTime sleepTime, System.DateTime wakeTime, int sleepScore, string notes) {
            SleepMonitorClient.SleepServiceRef.AddSleepEntryRequest inValue = new SleepMonitorClient.SleepServiceRef.AddSleepEntryRequest();
            inValue.Body = new SleepMonitorClient.SleepServiceRef.AddSleepEntryRequestBody();
            inValue.Body.sleepTime = sleepTime;
            inValue.Body.wakeTime = wakeTime;
            inValue.Body.sleepScore = sleepScore;
            inValue.Body.notes = notes;
            return ((SleepMonitorClient.SleepServiceRef.SleepServiceSoap)(this)).AddSleepEntryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SleepMonitorClient.SleepServiceRef.UpdateSleepEntryResponse SleepMonitorClient.SleepServiceRef.SleepServiceSoap.UpdateSleepEntry(SleepMonitorClient.SleepServiceRef.UpdateSleepEntryRequest request) {
            return base.Channel.UpdateSleepEntry(request);
        }
        
        public string UpdateSleepEntry(int id, System.DateTime sleepTime, System.DateTime wakeTime, int sleepScore, string notes) {
            SleepMonitorClient.SleepServiceRef.UpdateSleepEntryRequest inValue = new SleepMonitorClient.SleepServiceRef.UpdateSleepEntryRequest();
            inValue.Body = new SleepMonitorClient.SleepServiceRef.UpdateSleepEntryRequestBody();
            inValue.Body.id = id;
            inValue.Body.sleepTime = sleepTime;
            inValue.Body.wakeTime = wakeTime;
            inValue.Body.sleepScore = sleepScore;
            inValue.Body.notes = notes;
            SleepMonitorClient.SleepServiceRef.UpdateSleepEntryResponse retVal = ((SleepMonitorClient.SleepServiceRef.SleepServiceSoap)(this)).UpdateSleepEntry(inValue);
            return retVal.Body.UpdateSleepEntryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SleepMonitorClient.SleepServiceRef.UpdateSleepEntryResponse> SleepMonitorClient.SleepServiceRef.SleepServiceSoap.UpdateSleepEntryAsync(SleepMonitorClient.SleepServiceRef.UpdateSleepEntryRequest request) {
            return base.Channel.UpdateSleepEntryAsync(request);
        }
        
        public System.Threading.Tasks.Task<SleepMonitorClient.SleepServiceRef.UpdateSleepEntryResponse> UpdateSleepEntryAsync(int id, System.DateTime sleepTime, System.DateTime wakeTime, int sleepScore, string notes) {
            SleepMonitorClient.SleepServiceRef.UpdateSleepEntryRequest inValue = new SleepMonitorClient.SleepServiceRef.UpdateSleepEntryRequest();
            inValue.Body = new SleepMonitorClient.SleepServiceRef.UpdateSleepEntryRequestBody();
            inValue.Body.id = id;
            inValue.Body.sleepTime = sleepTime;
            inValue.Body.wakeTime = wakeTime;
            inValue.Body.sleepScore = sleepScore;
            inValue.Body.notes = notes;
            return ((SleepMonitorClient.SleepServiceRef.SleepServiceSoap)(this)).UpdateSleepEntryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SleepMonitorClient.SleepServiceRef.GetAllSleepEntriesResponse SleepMonitorClient.SleepServiceRef.SleepServiceSoap.GetAllSleepEntries(SleepMonitorClient.SleepServiceRef.GetAllSleepEntriesRequest request) {
            return base.Channel.GetAllSleepEntries(request);
        }
        
        public SleepMonitorClient.SleepServiceRef.SleepEntry[] GetAllSleepEntries() {
            SleepMonitorClient.SleepServiceRef.GetAllSleepEntriesRequest inValue = new SleepMonitorClient.SleepServiceRef.GetAllSleepEntriesRequest();
            inValue.Body = new SleepMonitorClient.SleepServiceRef.GetAllSleepEntriesRequestBody();
            SleepMonitorClient.SleepServiceRef.GetAllSleepEntriesResponse retVal = ((SleepMonitorClient.SleepServiceRef.SleepServiceSoap)(this)).GetAllSleepEntries(inValue);
            return retVal.Body.GetAllSleepEntriesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SleepMonitorClient.SleepServiceRef.GetAllSleepEntriesResponse> SleepMonitorClient.SleepServiceRef.SleepServiceSoap.GetAllSleepEntriesAsync(SleepMonitorClient.SleepServiceRef.GetAllSleepEntriesRequest request) {
            return base.Channel.GetAllSleepEntriesAsync(request);
        }
        
        public System.Threading.Tasks.Task<SleepMonitorClient.SleepServiceRef.GetAllSleepEntriesResponse> GetAllSleepEntriesAsync() {
            SleepMonitorClient.SleepServiceRef.GetAllSleepEntriesRequest inValue = new SleepMonitorClient.SleepServiceRef.GetAllSleepEntriesRequest();
            inValue.Body = new SleepMonitorClient.SleepServiceRef.GetAllSleepEntriesRequestBody();
            return ((SleepMonitorClient.SleepServiceRef.SleepServiceSoap)(this)).GetAllSleepEntriesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SleepMonitorClient.SleepServiceRef.DeleteSleepEntryResponse SleepMonitorClient.SleepServiceRef.SleepServiceSoap.DeleteSleepEntry(SleepMonitorClient.SleepServiceRef.DeleteSleepEntryRequest request) {
            return base.Channel.DeleteSleepEntry(request);
        }
        
        public string DeleteSleepEntry(int id) {
            SleepMonitorClient.SleepServiceRef.DeleteSleepEntryRequest inValue = new SleepMonitorClient.SleepServiceRef.DeleteSleepEntryRequest();
            inValue.Body = new SleepMonitorClient.SleepServiceRef.DeleteSleepEntryRequestBody();
            inValue.Body.id = id;
            SleepMonitorClient.SleepServiceRef.DeleteSleepEntryResponse retVal = ((SleepMonitorClient.SleepServiceRef.SleepServiceSoap)(this)).DeleteSleepEntry(inValue);
            return retVal.Body.DeleteSleepEntryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SleepMonitorClient.SleepServiceRef.DeleteSleepEntryResponse> SleepMonitorClient.SleepServiceRef.SleepServiceSoap.DeleteSleepEntryAsync(SleepMonitorClient.SleepServiceRef.DeleteSleepEntryRequest request) {
            return base.Channel.DeleteSleepEntryAsync(request);
        }
        
        public System.Threading.Tasks.Task<SleepMonitorClient.SleepServiceRef.DeleteSleepEntryResponse> DeleteSleepEntryAsync(int id) {
            SleepMonitorClient.SleepServiceRef.DeleteSleepEntryRequest inValue = new SleepMonitorClient.SleepServiceRef.DeleteSleepEntryRequest();
            inValue.Body = new SleepMonitorClient.SleepServiceRef.DeleteSleepEntryRequestBody();
            inValue.Body.id = id;
            return ((SleepMonitorClient.SleepServiceRef.SleepServiceSoap)(this)).DeleteSleepEntryAsync(inValue);
        }
    }
}
