//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SleepMonitorClient.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://sleepmonitor.org/", ConfigurationName="ServiceReference.SleepServiceSoap")]
    public interface SleepServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sleepmonitor.org/AddSleepEntry", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string AddSleepEntry(System.DateTime sleepTime, System.DateTime wakeTime, int sleepScore, string notes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sleepmonitor.org/AddSleepEntry", ReplyAction="*")]
        System.Threading.Tasks.Task<string> AddSleepEntryAsync(System.DateTime sleepTime, System.DateTime wakeTime, int sleepScore, string notes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sleepmonitor.org/UpdateSleepEntry", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string UpdateSleepEntry(int id, System.DateTime sleepTime, System.DateTime wakeTime, int sleepScore, string notes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sleepmonitor.org/UpdateSleepEntry", ReplyAction="*")]
        System.Threading.Tasks.Task<string> UpdateSleepEntryAsync(int id, System.DateTime sleepTime, System.DateTime wakeTime, int sleepScore, string notes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sleepmonitor.org/GetAllSleepEntries", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SleepMonitorClient.ServiceReference.SleepEntry[] GetAllSleepEntries();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sleepmonitor.org/GetAllSleepEntries", ReplyAction="*")]
        System.Threading.Tasks.Task<SleepMonitorClient.ServiceReference.SleepEntry[]> GetAllSleepEntriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sleepmonitor.org/DeleteSleepEntry", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string DeleteSleepEntry(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sleepmonitor.org/DeleteSleepEntry", ReplyAction="*")]
        System.Threading.Tasks.Task<string> DeleteSleepEntryAsync(int id);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sleepmonitor.org/")]
    public partial class SleepEntry : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private System.DateTime sleepTimeField;
        
        private System.DateTime wakeTimeField;
        
        private int sleepScoreField;
        
        private string notesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime SleepTime {
            get {
                return this.sleepTimeField;
            }
            set {
                this.sleepTimeField = value;
                this.RaisePropertyChanged("SleepTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime WakeTime {
            get {
                return this.wakeTimeField;
            }
            set {
                this.wakeTimeField = value;
                this.RaisePropertyChanged("WakeTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int SleepScore {
            get {
                return this.sleepScoreField;
            }
            set {
                this.sleepScoreField = value;
                this.RaisePropertyChanged("SleepScore");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Notes {
            get {
                return this.notesField;
            }
            set {
                this.notesField = value;
                this.RaisePropertyChanged("Notes");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SleepServiceSoapChannel : SleepMonitorClient.ServiceReference.SleepServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SleepServiceSoapClient : System.ServiceModel.ClientBase<SleepMonitorClient.ServiceReference.SleepServiceSoap>, SleepMonitorClient.ServiceReference.SleepServiceSoap {
        
        public SleepServiceSoapClient() {
        }
        
        public SleepServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SleepServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SleepServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SleepServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string AddSleepEntry(System.DateTime sleepTime, System.DateTime wakeTime, int sleepScore, string notes) {
            return base.Channel.AddSleepEntry(sleepTime, wakeTime, sleepScore, notes);
        }
        
        public System.Threading.Tasks.Task<string> AddSleepEntryAsync(System.DateTime sleepTime, System.DateTime wakeTime, int sleepScore, string notes) {
            return base.Channel.AddSleepEntryAsync(sleepTime, wakeTime, sleepScore, notes);
        }
        
        public string UpdateSleepEntry(int id, System.DateTime sleepTime, System.DateTime wakeTime, int sleepScore, string notes) {
            return base.Channel.UpdateSleepEntry(id, sleepTime, wakeTime, sleepScore, notes);
        }
        
        public System.Threading.Tasks.Task<string> UpdateSleepEntryAsync(int id, System.DateTime sleepTime, System.DateTime wakeTime, int sleepScore, string notes) {
            return base.Channel.UpdateSleepEntryAsync(id, sleepTime, wakeTime, sleepScore, notes);
        }
        
        public SleepMonitorClient.ServiceReference.SleepEntry[] GetAllSleepEntries() {
            return base.Channel.GetAllSleepEntries();
        }
        
        public System.Threading.Tasks.Task<SleepMonitorClient.ServiceReference.SleepEntry[]> GetAllSleepEntriesAsync() {
            return base.Channel.GetAllSleepEntriesAsync();
        }
        
        public string DeleteSleepEntry(int id) {
            return base.Channel.DeleteSleepEntry(id);
        }
        
        public System.Threading.Tasks.Task<string> DeleteSleepEntryAsync(int id) {
            return base.Channel.DeleteSleepEntryAsync(id);
        }
    }
}
