//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SleepMonitorClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://sleepmonitor.org/", ConfigurationName="ServiceReference1.SleepServiceSoap")]
    public interface SleepServiceSoap {
        
        // CODEGEN: Generating message contract since element name notes from namespace http://sleepmonitor.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://sleepmonitor.org/AddSleepEntry", ReplyAction="*")]
        SleepMonitorClient.ServiceReference1.AddSleepEntryResponse AddSleepEntry(SleepMonitorClient.ServiceReference1.AddSleepEntryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sleepmonitor.org/AddSleepEntry", ReplyAction="*")]
        System.Threading.Tasks.Task<SleepMonitorClient.ServiceReference1.AddSleepEntryResponse> AddSleepEntryAsync(SleepMonitorClient.ServiceReference1.AddSleepEntryRequest request);
        
        // CODEGEN: Generating message contract since element name notes from namespace http://sleepmonitor.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://sleepmonitor.org/UpdateSleepEntry", ReplyAction="*")]
        SleepMonitorClient.ServiceReference1.UpdateSleepEntryResponse UpdateSleepEntry(SleepMonitorClient.ServiceReference1.UpdateSleepEntryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sleepmonitor.org/UpdateSleepEntry", ReplyAction="*")]
        System.Threading.Tasks.Task<SleepMonitorClient.ServiceReference1.UpdateSleepEntryResponse> UpdateSleepEntryAsync(SleepMonitorClient.ServiceReference1.UpdateSleepEntryRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddSleepEntryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddSleepEntry", Namespace="http://sleepmonitor.org/", Order=0)]
        public SleepMonitorClient.ServiceReference1.AddSleepEntryRequestBody Body;
        
        public AddSleepEntryRequest() {
        }
        
        public AddSleepEntryRequest(SleepMonitorClient.ServiceReference1.AddSleepEntryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://sleepmonitor.org/")]
    public partial class AddSleepEntryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime sleepTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime wakeTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int sleepScore;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string notes;
        
        public AddSleepEntryRequestBody() {
        }
        
        public AddSleepEntryRequestBody(System.DateTime sleepTime, System.DateTime wakeTime, int sleepScore, string notes) {
            this.sleepTime = sleepTime;
            this.wakeTime = wakeTime;
            this.sleepScore = sleepScore;
            this.notes = notes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddSleepEntryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddSleepEntryResponse", Namespace="http://sleepmonitor.org/", Order=0)]
        public SleepMonitorClient.ServiceReference1.AddSleepEntryResponseBody Body;
        
        public AddSleepEntryResponse() {
        }
        
        public AddSleepEntryResponse(SleepMonitorClient.ServiceReference1.AddSleepEntryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://sleepmonitor.org/")]
    public partial class AddSleepEntryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddSleepEntryResult;
        
        public AddSleepEntryResponseBody() {
        }
        
        public AddSleepEntryResponseBody(string AddSleepEntryResult) {
            this.AddSleepEntryResult = AddSleepEntryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateSleepEntryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateSleepEntry", Namespace="http://sleepmonitor.org/", Order=0)]
        public SleepMonitorClient.ServiceReference1.UpdateSleepEntryRequestBody Body;
        
        public UpdateSleepEntryRequest() {
        }
        
        public UpdateSleepEntryRequest(SleepMonitorClient.ServiceReference1.UpdateSleepEntryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://sleepmonitor.org/")]
    public partial class UpdateSleepEntryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime sleepTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime wakeTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int sleepScore;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string notes;
        
        public UpdateSleepEntryRequestBody() {
        }
        
        public UpdateSleepEntryRequestBody(int id, System.DateTime sleepTime, System.DateTime wakeTime, int sleepScore, string notes) {
            this.id = id;
            this.sleepTime = sleepTime;
            this.wakeTime = wakeTime;
            this.sleepScore = sleepScore;
            this.notes = notes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateSleepEntryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateSleepEntryResponse", Namespace="http://sleepmonitor.org/", Order=0)]
        public SleepMonitorClient.ServiceReference1.UpdateSleepEntryResponseBody Body;
        
        public UpdateSleepEntryResponse() {
        }
        
        public UpdateSleepEntryResponse(SleepMonitorClient.ServiceReference1.UpdateSleepEntryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://sleepmonitor.org/")]
    public partial class UpdateSleepEntryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdateSleepEntryResult;
        
        public UpdateSleepEntryResponseBody() {
        }
        
        public UpdateSleepEntryResponseBody(string UpdateSleepEntryResult) {
            this.UpdateSleepEntryResult = UpdateSleepEntryResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SleepServiceSoapChannel : SleepMonitorClient.ServiceReference1.SleepServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SleepServiceSoapClient : System.ServiceModel.ClientBase<SleepMonitorClient.ServiceReference1.SleepServiceSoap>, SleepMonitorClient.ServiceReference1.SleepServiceSoap {
        
        public SleepServiceSoapClient() {
        }
        
        public SleepServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SleepServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SleepServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SleepServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SleepMonitorClient.ServiceReference1.AddSleepEntryResponse SleepMonitorClient.ServiceReference1.SleepServiceSoap.AddSleepEntry(SleepMonitorClient.ServiceReference1.AddSleepEntryRequest request) {
            return base.Channel.AddSleepEntry(request);
        }
        
        public string AddSleepEntry(System.DateTime sleepTime, System.DateTime wakeTime, int sleepScore, string notes) {
            SleepMonitorClient.ServiceReference1.AddSleepEntryRequest inValue = new SleepMonitorClient.ServiceReference1.AddSleepEntryRequest();
            inValue.Body = new SleepMonitorClient.ServiceReference1.AddSleepEntryRequestBody();
            inValue.Body.sleepTime = sleepTime;
            inValue.Body.wakeTime = wakeTime;
            inValue.Body.sleepScore = sleepScore;
            inValue.Body.notes = notes;
            SleepMonitorClient.ServiceReference1.AddSleepEntryResponse retVal = ((SleepMonitorClient.ServiceReference1.SleepServiceSoap)(this)).AddSleepEntry(inValue);
            return retVal.Body.AddSleepEntryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SleepMonitorClient.ServiceReference1.AddSleepEntryResponse> SleepMonitorClient.ServiceReference1.SleepServiceSoap.AddSleepEntryAsync(SleepMonitorClient.ServiceReference1.AddSleepEntryRequest request) {
            return base.Channel.AddSleepEntryAsync(request);
        }
        
        public System.Threading.Tasks.Task<SleepMonitorClient.ServiceReference1.AddSleepEntryResponse> AddSleepEntryAsync(System.DateTime sleepTime, System.DateTime wakeTime, int sleepScore, string notes) {
            SleepMonitorClient.ServiceReference1.AddSleepEntryRequest inValue = new SleepMonitorClient.ServiceReference1.AddSleepEntryRequest();
            inValue.Body = new SleepMonitorClient.ServiceReference1.AddSleepEntryRequestBody();
            inValue.Body.sleepTime = sleepTime;
            inValue.Body.wakeTime = wakeTime;
            inValue.Body.sleepScore = sleepScore;
            inValue.Body.notes = notes;
            return ((SleepMonitorClient.ServiceReference1.SleepServiceSoap)(this)).AddSleepEntryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SleepMonitorClient.ServiceReference1.UpdateSleepEntryResponse SleepMonitorClient.ServiceReference1.SleepServiceSoap.UpdateSleepEntry(SleepMonitorClient.ServiceReference1.UpdateSleepEntryRequest request) {
            return base.Channel.UpdateSleepEntry(request);
        }
        
        public string UpdateSleepEntry(int id, System.DateTime sleepTime, System.DateTime wakeTime, int sleepScore, string notes) {
            SleepMonitorClient.ServiceReference1.UpdateSleepEntryRequest inValue = new SleepMonitorClient.ServiceReference1.UpdateSleepEntryRequest();
            inValue.Body = new SleepMonitorClient.ServiceReference1.UpdateSleepEntryRequestBody();
            inValue.Body.id = id;
            inValue.Body.sleepTime = sleepTime;
            inValue.Body.wakeTime = wakeTime;
            inValue.Body.sleepScore = sleepScore;
            inValue.Body.notes = notes;
            SleepMonitorClient.ServiceReference1.UpdateSleepEntryResponse retVal = ((SleepMonitorClient.ServiceReference1.SleepServiceSoap)(this)).UpdateSleepEntry(inValue);
            return retVal.Body.UpdateSleepEntryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SleepMonitorClient.ServiceReference1.UpdateSleepEntryResponse> SleepMonitorClient.ServiceReference1.SleepServiceSoap.UpdateSleepEntryAsync(SleepMonitorClient.ServiceReference1.UpdateSleepEntryRequest request) {
            return base.Channel.UpdateSleepEntryAsync(request);
        }
        
        public System.Threading.Tasks.Task<SleepMonitorClient.ServiceReference1.UpdateSleepEntryResponse> UpdateSleepEntryAsync(int id, System.DateTime sleepTime, System.DateTime wakeTime, int sleepScore, string notes) {
            SleepMonitorClient.ServiceReference1.UpdateSleepEntryRequest inValue = new SleepMonitorClient.ServiceReference1.UpdateSleepEntryRequest();
            inValue.Body = new SleepMonitorClient.ServiceReference1.UpdateSleepEntryRequestBody();
            inValue.Body.id = id;
            inValue.Body.sleepTime = sleepTime;
            inValue.Body.wakeTime = wakeTime;
            inValue.Body.sleepScore = sleepScore;
            inValue.Body.notes = notes;
            return ((SleepMonitorClient.ServiceReference1.SleepServiceSoap)(this)).UpdateSleepEntryAsync(inValue);
        }
    }
}
